settings analytics
barracuda-cloudgen-access/access-cli pull request #57
Opened 2021-06-06 20:35 UTC by oNaiPs

2021-06-07 18:57 UTC, pablosole requested changes
I think you need to merge the other PR about settings first (already approved) and rebase this changes to it

2021-06-07 18:57 UTC, pablosole commented on cmd/add-resources.go
> +						resource.FixedLastOctet.AssignFromString(s)
you put it on the other PR about settings

2021-06-07 18:57 UTC, pablosole commented on cmd/common-input.go
> +		if len(setterFuncs) != len(data.fields) {
ditto

2021-06-07 18:57 UTC, pablosole commented on cmd/settings-analytics-set.go
> +			FlagName:        "external_server_intercept_all_domains",
this flags are super verbose

2021-06-08 12:21 UTC, oNaiPs commented
@pablosole fixed

2021-06-08 13:05 UTC, oNaiPs commented on cmd/settings-analytics-set.go
> +			FlagName:        "external_server_intercept_all_domains",
fixed

2021-06-08 22:23 UTC, pablosole approved these changes

2021-06-09 15:16 UTC, merged